Lab1
jks-sn/NSULabs_Java pull request #1
Opened 2023-03-01 15:31 UTC by jks-sn

2023-03-18 06:05 UTC, tematre requested changes

2023-03-18 06:05 UTC, tematre commented on srs/calculator/factory/ConfigParser.java
> +        try {
Это можно заменить одним try

2023-03-18 06:05 UTC, tematre commented on srs/calculator/log/Log.java
> +public class Log {
Это лучше удалить

2023-03-18 06:31 UTC, jks-sn commented on srs/calculator/factory/ConfigParser.java
> +        try {
поправил

2023-03-18 07:12 UTC, tematre approved these changes

2023-05-27 05:05 UTC, tematre commented
Лаба принята

2023-05-27 05:12 UTC, merged